### ISSUE TITLE
Could rbg2p report an error if a variable in a rule is not previously defined?

### ISSUE THREAD

**Issue by HannaLindgren** [stts-se/rbg2p#3]
I would like to get an error in the following case:

```
VAR CHARSET (a|b|c)
...
a -> A / _ HCARSET

```
where the variable is wrong.

**Comment by NikolajLindberg** [comment]
Me too!

**Comment by HannaLindgren** [comment]
It now fails if the context matches /[A-Z]{2,}/ OCH /^[A-Z0-9]{2,}$/. Not sure if this is right or not.

**Comment by HannaLindgren** [comment]
It is not entirely easy to determine if a specified context is a variable or a regexp... It now fails if the context matches /^[A-Z]/ AND /^[A-Z0-9]{2,}$

Will close for now, but see also _#5: Use of variables should always be surrounded by brackets_
